### ISSUE TITLE
[hackathon] shift2bikes calendar

### ISSUE THREAD

**Issue by ungoldman** [code-for-portland-archive/ideas#12]
@onehwang mentioned that there's a plan in the works with CCC for a hackathon to improve the Shift Calendar - http://www.shift2bikes.org/cal/

**Comment by ungoldman** [comment]
@meandavejustice mentioned something about a calendar for bike & activist events in town -- I mentioned this project along with http://portland.activatehub.org/ as preexisting projects with similar goals.

**Comment by OneHwang** [comment]
The Shift Calendar Hackathon will (1) improve the source code for the Shift Calendar so that it is prettier, easier to use, and interoperable with social media and (2) form a community of diverse people who are empowered to make contributions to technology that advance bicycling. When: Saturday, September 12. Who: hackers who know php, css, and javascript (and possibly copywriters). Where -  @ngoldman, can you ask ESRI if they can accommodate us from 8:30 AM to 6PM? Also, what would be the capacity? We can require registration in advance and limit the number of registrants to the capacity. Thanks.

**Comment by OneHwang** [comment]
@ngoldman - I hope everything's well. ESRI UC was amazing! Would ESRI-PDX be willing to host the Shift Cal Hackathon on Sept. 12?  I appreciate your help!

**Comment by ungoldman** [comment]
@OneHwang: I think it should be possible! I need to talk with @JerrySievert about it and then I'll get back to you.

**Comment by ungoldman** [comment]
@OneHwang: I talked with @JerrySievert and he said it's fine. We just need to limit the number of attendees to 25.

**Comment by OneHwang** [comment]
Thanks @ngoldman and @JerrySievert !

**Comment by OneHwang** [comment]
@ngoldman - can you help spread the word to the Code for Portland community? The event details are here: http://www.meetup.com/Techies-On-Bikes/events/224752422/

**Comment by ungoldman** [comment]
@OneHwang done! https://twitter.com/CodeforPortland/status/636692565304053760

**Comment by OneHwang** [comment]
Thank you!
